### ISSUE TITLE
Examples on rendering scenes

### ISSUE THREAD

**Issue by Ananyapam7** [mitkonikov/manim-code#3]
I have tried running the code and it does not throw any errors, but it says 'There are no scenes inside that module'. Can you please add some examples on rendering this in a scene, will be a great help.

**Comment by mitkonikov** [comment]
Yes, of course, below is a file that might help you. But I started to update the library for the new Manim v0.6.0 and there are few changes in the new version that affect this code. But, in a couple of days, I will figure everything out and it will be compatible with the new Manim.

[Array Example](https://github.com/mitkonikov/manim-code/files/6475537/array_main.zip)

Have fun animating!

**Comment by Ananyapam7** [comment]
Thanks a lot! I had to modify some lines in the code, the first was the imports at the top where I had to change it to 
`from manimlib.imports import *`

and for the Tex objects, I replaced them by TextMobjects, which did the trick in rendering. Thank you very much!!
